### ISSUE TITLE
Odd message when eating poisonous corpse

### ISSUE THREAD

**Issue by k21971** [k21971/EvilHack#1]
After implementing the partial resistance commit, now when a player eats a poisonous corpse, they get a message like this:
`Ecch - that must have been poisonous!  incoming: 2  outgoing: 2  incoming: 14  outgoing: 14`
The first incoming/outgoing values are the drop in STR, the second set of values are the HP lost. No errors that I can see, the game still goes on as normal, and any partial resistances that would be granted are given. Just need to figure out how to suppress the incoming/outgoing data.

**Comment by k21971** [comment]
Resolved via commit 01fa071

**Comment by luckybulldozer** [comment]
Can't wait to try EvilHack!  I've got an Xcode build error on line 3319 mhitu.c "Control reaches end of non-void function". -- pretty sure I've got my developer cert number entered correctly. Cheers!

**Comment by k21971** [comment]
That closing bracket at line 3319, right below it, add this:
return 0;

Recompile and see how that works.

- Keith
