### ISSUE TITLE
Zapping self with slow monster doesn't always cause slowness.

### ISSUE THREAD

**Issue by elunna** [k21971/EvilHack#103]
It appears that you have to have the Fast intrinsic to become slowed from wands or spells of slow monster:

zap.c: 2760
    case WAN_SLOW_MONSTER:
    case SPE_SLOW_MONSTER:
        if (HFast & (TIMEOUT | INTRINSIC)) {
            learn_it = TRUE;
            u_slow_down();
        }
        break;

**Comment by k21971** [comment]
Closed via commit 925601c.
