### ISSUE TITLE
Cursed wands of invisibility cannot revert intrinsic invisibility

### ISSUE THREAD

**Issue by elunna** [k21971/EvilHack#105]
You get permanent invisibility from a magic trap, but you cannot zap yourself with a cursed wand of make invisible to become visible again ("You fade from view for a brief moment.").

This check excludes intrinsic invisiblity, so only temporary invisibility will be reverted.
if (!EInvis && (HInvis & TIMEOUT) && obj->cursed) {

**Comment by entrez** [comment]
I would have guessed that was intentional, since it explicitly uses the `TIMEOUT` mask.  Doesn't really look like an unintended side effect or anything, just going off the code...

**Comment by k21971** [comment]
> I would have guessed that was intentional, since it explicitly uses the `TIMEOUT` mask. Doesn't really look like an unintended side effect or anything, just going off that snippet of code... Is there code within that block that does handle removal of permanent invisibility?

It looks like this was intentional, but I don't think it was. I'm not sure what past me was thinking here, the intent was to negate invisibility, whether it was temporary or permanent.

**Comment by k21971** [comment]
Fixed via commit 5b7b662.
