### ISSUE TITLE
Wishing for 'helm of telepathy' collides with 'telepathy' property

### ISSUE THREAD

**Issue by stenno** [k21971/EvilHack#108]
Wishing for 'a helm of telepathy' will (might?) result in a random helm with the 'telepathy' property. This is problematic as the actual item 'helm of telepathy' still exists in the game. Either the item should be removed, or readobjnam should do strict matching for existing items with that name before considering properties.
See this bug 'in action' in this reddit thread: https://www.reddit.com/r/nethack/comments/z86oht/i_wished_for_a_helm_of_telepathy_but_got_opposite/

**Comment by stenno** [comment]
The same issue should arise for 'gauntlets of fumbling' and 'boots of fumbling'.

**Comment by k21971** [comment]
Nice find stenno. I hate you 😁

**Comment by k21971** [comment]
The easiest way to address this, is to simply rename the object properties 'telepathy' and 'fumbling' to something else that does not conflict with already existing magical objects that have those words as part of their description. I'll play around with some changes in objnam.c and see what happens.

**Comment by stenno** [comment]
> 

Luckily, at least for telepathy, that is already the case ("ESP" works too)

**Comment by k21971** [comment]
I actually figured this one out. Fixed via commit 0edfa07.
