### ISSUE TITLE
Player-race intrinsics are carried over to polyforms

### ISSUE THREAD

**Issue by elunna** [k21971/EvilHack#111]
The implementation of races allows for a player's polyform to inherit all of the intrinsics that the player has built up to that point from it's racial side.

As an example, an illithid priest (above level 12 so it has flying) can polymorph into a minotaur that has flying. It will also have telepathy and psychic resistance from ill_abil. 

For giants, this means no matter what they poly into they aggravate monsters.

For centaurs above level 5, they might poly into something that shouldn't have jumping innately. Etc, etc.

**Comment by k21971** [comment]
This isn't a bug. Several race-based intrinsics carry over when you polyform into something else (e.g. player as an elf with sleep resistance will keep that intrinsic if they polymorph into <monster>). Some intrinsics that carry over may not make as much sense as others, I'll give you that.
