### ISSUE TITLE
Scroll of teleportation message says "different location" even when you materialize in the same location

### ISSUE THREAD

**Issue by loggersviii** [k21971/EvilHack#113]
Pretty self explanatory. When selected to teleport to the square you are already on using a scroll (and perhaps other means), the game still prints "you materialize in a different location!". Strangely, it also doesn't auto-ID the scroll. I'm not sure if this also applies to rings, wands, telecontrolled teleportitis, etc.

**Comment by k21971** [comment]
I just tried to recreate this, and didn't. Had a ring of teleport control on, had an uncursed un-ID'ed scroll of teleportation. Read the scroll, picked my same location, received 'You materialize in the same location!' for feedback, and checked my discoveries list - scroll of teleportation was now known.

**Comment by loggersviii** [comment]
hmm that's strange. I'll try and dig through the ttyrecs to see if I can find it.
