### ISSUE TITLE
Stairway to Heaven

### ISSUE THREAD

**Issue by mightyquinjet** [k21971/EvilHack#154]
The Hammer of the Gods is a forged artifact in EvilHack. It is also the title of a biography of Led Zeppelin. In keeping with the other enhancements to forged artifacts, the Hammer could be used to create a single-use stairway to the next-higher level upon invocation. Or, for simplicity, perhaps it could have exactly the same invocation behavior as the Eye of the Aethiopica instead.

—What do you want to invoke?
—You #Invoke the Hammer of the Gods.
—A shimmering golden cloud appears before you!
—You hear a celestial guitar playing an overly-familiar melody!
—Do you want to ascend? (Y/N)
—Y
—You ascend the Stairway to Heaven!
—The Stairway vanishes!

Or:

—What do you want to invoke?
—You #Invoke the Hammer of the Gods.
—A shimmering golden cloud appears before you!
—You hear a celestial guitar playing an overly-familiar melody!
—To what branch do you wish to teleport?
—The Astral Plane
—The voice of Thor rings out, “No mortal! That shall not be done!”
—The Stairway vanishes!
—What do you want to invoke?
—You #Invoke the Hammer of the Gods.
—You feel the Hammer of the Gods is ignoring you. 

What do you think?

**Comment by loggersviii** [comment]
it's funny, but why open an issue for a YASI?

**Comment by mightyquinjet** [comment]
Most likely because I misunderstood the way things are done here. Sorry about that 🫢.  Closing.

**Comment by mightyquinjet** [comment]
Because I misunderstood the purpose of issues. Sorry about that. Is there a repository of YASIs that would be better to use?*********************************Ed ***@***.***+1-610-329-9077 mobileOn Sep 26, 2023, at 10:25 AM, loggersviii ***@***.***> wrote:﻿
it's funny, but why open an issue for a YASI?

**Comment by entrez** [comment]
I don't think this is an inappropriate place to put it if you were serious about the idea (though I don't think it's likely to get traction).  If you were joking (if it was really a YASI and not meant to be seriously considered), then yes, it's probably not great to add clutter to the issues with a joke.  I don't think there's any sort of repository of joke suggestions.

**Comment by mightyquinjet** [comment]
Thanks for the clarification, Michael. It was indeed seriously intended, and I would not intentionally clutter the repository with bad ideas. I’ll refrain from posting anything else that is not well thought out.Best regards,*********************************Ed ***@***.***+1-610-329-9077 mobileOn Sep 26, 2023, at 11:52 AM, Michael Meyer ***@***.***> wrote:﻿
I don't think this is an inappropriate place to put it if you were serious about the idea (though I don't think it's likely to get traction).  If you were joking (if it was really a YASI and not meant to be seriously considered), then yes, it's probably not great to add clutter to the issues with a joke.  I don't think there's any sort of repository of joke suggestions.

**Comment by k21971** [comment]
@mightyquinjet it's fine posting ideas here. I appreciate your suggestions, but I'm not looking to add any extra abilities to the HotG, it's pretty powerful as it stands.

**Comment by mightyquinjet** [comment]
Thanks for the feedback, Keith. I do think that it adds some flavor to give the new forged artifacts some #invocation  abilities, so long as they are not overpowered. Creating a temporary upstairs is an interesting substitute for cursed !oGL. Best,*********************************Ed ***@***.***+1-610-329-9077 mobileOn Sep 26, 2023, at 5:41 PM, Keith Simpson ***@***.***> wrote:﻿
@mightyquinjet it's fine posting ideas here. I appreciate your suggestions, but I'm not looking to add any extra abilities to the HotG, it's pretty powerful as it stands.

**Comment by mightyquinjet** [comment]
Keith,

I’m playing an EvilHack game on the HF server right now. I found and equipped a ‘polished shield’, with no material specified. When I melee with a homunculus, I get the message ’the polished silver shield sears the homunculus’ flesh!’.

I think that the silver sear damage must have been hard coded into the structure of the shield of reflection, and then survived the update to object materials.

Related question: What are elven armor and weapons made of? The wiki says:
Armor and weapons of elven make (except cloth items):
60% its base material
20% wood
10% copper
5% mithril
3% silver
2% gold

What would those base materials be for, say, an elven dagger or helm?

Thanks as always for the continuing updates to EvilHack.

Best,

***********

Ed Gooding
***@***.***
