### ISSUE TITLE
Chaotic convict feels guilty about stealing?

### ISSUE THREAD

**Issue by jkoudys** [k21971/EvilHack#168]
My name is literally "Connie the Crook", and I abuse my alignment when I phase into a shop (that wouldn't let me in, to boot) and leave without paying. Character's chaotic, too.

**Comment by k21971** [comment]
Duly noted. Easy to reproduce - will fix this for next version.

**Comment by jkoudys** [comment]
Thanks! I get "guilty" from shift-F robbing peaceful monsters (even shopkeepers or cross-aligned priests). Where's the fun in being chaotic if I feel bad about everything?

**Comment by k21971** [comment]
Fixed via commit 31fa8ba (this will appear in future version 0.9.0)
