### ISSUE TITLE
Convict feeling guilty for robbing a bank vault?

### ISSUE THREAD

**Issue by jkoudys** [k21971/EvilHack#174]
If ever there were a role that shouldn't abuse their alignment by robbing a bank, it's the convict.

Built on Mar 26 fb5d1d1d1c71ab47c55a2329eac977a80ce030b9

**Comment by mobi-leuser** [comment]
good catch, there was already a commit to stop convicts feeling guilty robbing shops:
https://github.com/k21971/EvilHack/commit/31fa8ba8d99eb515454b134efae5ac87c3663225
so vaults should be fair game too (I assume you mean the case where a guard appears)

**Comment by k21971** [comment]
Looking into it now...

**Comment by k21971** [comment]
Fixed via commit dc9b3d5
