### ISSUE TITLE
Minor gold detection bug

### ISSUE THREAD

**Issue by Doesnty** [k21971/EvilHack#67]
Hi, was porting the object materials from this over to a variant I'm working on and spotted a minor bug:

o_material() in src/detect.c checks the material of variable obj in the loop; it should be checking otmp, which it's actually looping through. As-is, it will fail to spot any items of the desired material inside containers, unless those items happen to be containers themselves.

I don't think this is used for anything but gold detection in vanilla, but might be significant if there's something else calling it I'm not aware of.

**Comment by k21971** [comment]
Hi Doesnty, good catch, and thanks for reporting it. I'll address this today.

**Comment by k21971** [comment]
See git commit 7708a51.

**Comment by NullCGT** [comment]
Thanks K2! Fixed!
