### ISSUE TITLE
Control reaches end of non-void function

### ISSUE THREAD

**Issue by luckybulldozer** [k21971/EvilHack#7]
Control reaches end of non-void function on line 3319 of mhitu.c
Can't wait to try EvilHack!

**Comment by k21971** [comment]
commit bc68681 may prevent that error from occurring when compiling under xcode. Pull from this repo again and give it another try.

**Comment by luckybulldozer** [comment]
No luck, I'm upto date ```ddc3870```, I should have mentioned I'm using Xcode.  Is there an easy way to build just using command line on OS X using GCC?

**Comment by k21971** [comment]
Yup I saw your email, looked up why xcode would give an error like that, why I added 'return 0;' at the end of that code block.
Unfortunately my experience with OS X is limited at best. I don't know. Maybe hop into channel #hardfought on Freenode IRC, there's a quite a few knowledge people there, might be able to help.
