### ISSUE TITLE
compile warnings; function ‘droppables’ may return address of local var

### ISSUE THREAD

**Issue by nabbi** [k21971/EvilHack#71]
Hello- When building on Gentoo the following QA warning is caught.

`dogmove.c: In function ‘droppables’:
cc1: warning: function may return address of local variable [-Wreturn-local-addr]
dogmove.c:266:28: note: declared here
dogmove.c:266:28: note: declared here
dogmove.c:266:28: note: declared here
dogmove.c:266:28: note: declared here
dogmove.c:266:28: note: declared here
dogmove.c:266:28: note: declared here
dogmove.c:266:28: note: declared here
`

Please advise what additional info is needed.
Thank you!

**Comment by k21971** [comment]
Hi nabbi. This same warning exists in vanilla nethack as well. We've been discussing this on IRC (#evilhack) about a possible solution. However, if your state of mind allows for it, you can safely ignore that warning.

**Comment by nabbi** [comment]
Cool. I'll append a note within the build script referencing this awareness. I'll defer to you if you desire to close or leave open for project tacking purposes. Thank you!

**Comment by k21971** [comment]
Thanks nabbi. I'll leave it open for now. My OCD doesn't like seeing the warning pop up every time when I compile :)

**Comment by k21971** [comment]
Resolved in git commit e5aac4f.
