### ISSUE TITLE
compile warnings; wintty.c implicit function 'open'

### ISSUE THREAD

**Issue by nabbi** [k21971/EvilHack#73]
Hello- When building on Gentoo the following QA notice is caught.

` ../win/tty/wintty.c:2830:27: warning: implicit declaration of function ‘open’; did you mean ‘popen’? [-Wimplicit-function-declaration]`

I was mistaken and closed [pull 72](https://github.com/k21971/EvilHack/pull/72), opening this issue to track the report.

Thank you!

**Comment by entrez** [comment]
Have you modified include/unixconf.h so that `DEF_PAGER` is defined (line 117)?  If so, try commenting that out for now so that EvilHack's built-in internal pager will be used instead.

**Comment by nabbi** [comment]
Thanks for the guidance. I am in the process of refreshing the ebuild and will remove that cflag.
It builds without this warning now.
