### ISSUE TITLE
Polymorphed Tortle werejackal has protective shell

### ISSUE THREAD

**Issue by CassiopeiaStar** [k21971/EvilHack#94]
I received the following message when playing as a Tortle and polymorphed into a jackal due to lycanthropy.

"Your protective shell blocks the monkey's attack."

**Comment by k21971** [comment]
Alright, there's one thing I didn't think of. Thanks for the report, I'm on it.

**Comment by k21971** [comment]
Fixed, see git commit 5d14ccb.
